//! The three phase reduction search (`cs.threephase.Search`).

use super::centers::{Center1, Center2, Center3};
use super::edge3::{Edge3, N_RAW};
use super::full_cube::FullCube;
use super::moves::{MOVE2STD, MOVE3STD, MOVES, WB3, WD3, WF1, WU1, to_moves};
use super::tables::{TABLES, Tables};
use crate::java::{JavaPriorityQueue, RandomSource};

const PHASE1_SOLUTIONS: usize = 10000;
const PHASE2_ATTEMPTS: usize = 500;
const PHASE2_SOLUTIONS: usize = 100;
const PHASE3_ATTEMPTS: usize = 100;

/// Chen Shuang's three phase 4x4x4 solver: phase 1 separates the U/D centers, phase 2
/// solves the remaining centers into a reduced state, phase 3 pairs the edges; the reduced
/// 3x3x3 is then solved with min2phase.
#[derive(Clone)]
pub struct Search {
    t: &'static Tables,
    p1sols: JavaPriorityQueue<FullCube>,
    move1: [usize; 15],
    move2: [usize; 20],
    move3: [usize; 20],
    length1: i32,
    length2: i32,
    add1: bool,
    c: FullCube,
    c1: FullCube,
    c2: FullCube,
    ct2: Center2,
    ct3: Center3,
    e12: Edge3,
    tempe: [Edge3; 20],
    search333: crate::min2phase::Search,
    solution: String,
    p1_sols_cnt: usize,
    arr2: Vec<FullCube>,
    arr2idx: usize,
    /// Return the inverse of the solution (a scramble); `true` by default.
    pub inverse_solution: bool,
    /// Append the whole-cube rotation that finishes the solution; `false` by default.
    pub with_rotation: bool,
    totlen: i32,
}

impl std::fmt::Debug for Search {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Search")
            .field("solution", &self.solution)
            .field("inverse_solution", &self.inverse_solution)
            .field("with_rotation", &self.with_rotation)
            .finish_non_exhaustive()
    }
}

impl Default for Search {
    fn default() -> Self {
        Self::new()
    }
}

/// `ValueComparator`: the queue keeps the phase 1 candidates with the *largest* estimate on
/// top, so that they are the first to be replaced.
fn by_value_descending(a: &FullCube, b: &FullCube) -> std::cmp::Ordering {
    b.value.cmp(&a.value)
}

impl Search {
    /// A new searcher; the lookup tables are built on first use.
    pub fn new() -> Self {
        Self {
            t: &TABLES,
            p1sols: JavaPriorityQueue::with_capacity(PHASE2_ATTEMPTS, by_value_descending),
            move1: [0; 15],
            move2: [0; 20],
            move3: [0; 20],
            length1: 0,
            length2: 0,
            add1: false,
            c: FullCube::new(),
            c1: FullCube::new(),
            c2: FullCube::new(),
            ct2: Center2::default(),
            ct3: Center3::default(),
            e12: Edge3::new(),
            tempe: [Edge3::new(); 20],
            search333: crate::min2phase::Search::new(),
            solution: String::new(),
            p1_sols_cnt: 0,
            arr2: Vec::with_capacity(PHASE2_SOLUTIONS),
            arr2idx: 0,
            inverse_solution: true,
            with_rotation: false,
            totlen: 0,
        }
    }

    /// Builds the lookup tables now instead of on the first solve.
    pub fn init() {
        let _ = &*TABLES;
    }

    /// Solves a random cube drawn from `r` (edges, centers, corners in that order).
    pub fn random_state(&mut self, r: &mut dyn RandomSource) -> String {
        self.c = FullCube::random(r);
        self.do_search();
        self.solution.clone()
    }

    /// Solves 40 random moves drawn from `r` (`randomMove`, without Java's debug print).
    pub fn random_move(&mut self, r: &mut dyn RandomSource) -> String {
        let ckmv = &MOVES.ckmv;
        let mut moveseq = [0; 40];
        let mut lm = 36;
        let mut i = 0;
        while i < moveseq.len() {
            let m = r.next_int_bounded(27) as usize;
            if !ckmv[lm][m] {
                moveseq[i] = m;
                i += 1;
                lm = m;
            }
        }
        self.solve_moves(&moveseq)
    }

    /// Solves a cube given as 96 facelets (`URFDLB` letters, 16 per face).
    ///
    /// # Panics
    ///
    /// Panics if `facelet` has fewer than 96 characters.
    pub fn solution(&mut self, facelet: &str) -> String {
        let mut f = [0_u8; 96];
        let chars: Vec<char> = facelet.chars().collect();
        for (i, v) in f.iter_mut().enumerate() {
            // Like Java, unknown letters become -1 (here 255) and match nothing.
            *v = "URFDLB".find(chars[i]).map_or(u8::MAX, |p| p as u8);
        }
        self.c = FullCube::from_facelets(&f);
        self.do_search();
        self.solution.clone()
    }

    /// Solves the cube generated by a scramble such as `"R U Rw' F2 l"`.
    pub fn solve(&mut self, scramble: &str) -> String {
        self.solve_moves(&to_moves(scramble))
    }

    /// Solves the cube generated by a sequence of moves (0..36).
    pub fn solve_moves(&mut self, moves: &[usize]) -> String {
        self.c = FullCube::from_moves(moves);
        self.do_search();
        self.solution.clone()
    }

    /// Solves `s` (`calc`).
    pub fn calc(&mut self, s: FullCube) {
        self.c = s;
        self.do_search();
    }

    /// The last solution.
    pub fn last_solution(&self) -> &str {
        &self.solution
    }

    /// The total length (all phases and the 3x3x3 stage) of the last solution.
    pub fn total_length(&self) -> i32 {
        self.totlen
    }

    fn do_search(&mut self) {
        let t = self.t;
        let c1t = &t.center1;
        self.solution.clear();
        let center = *self.c.center();
        let ud = Center1::from_center(&center, 0).get_sym(&c1t.sym2raw);
        let fb = Center1::from_center(&center, 1).get_sym(&c1t.sym2raw);
        let rl = Center1::from_center(&center, 2).get_sym(&c1t.sym2raw);
        let udprun = i32::from(c1t.csprun[(ud >> 6) as usize]);
        let fbprun = i32::from(c1t.csprun[(fb >> 6) as usize]);
        let rlprun = i32::from(c1t.csprun[(rl >> 6) as usize]);

        self.p1_sols_cnt = 0;
        self.arr2idx = 0;
        self.p1sols.clear();

        self.length1 = udprun.min(fbprun).min(rlprun);
        while self.length1 < 100 {
            let l = self.length1;
            if rlprun <= l && self.search1(rl >> 6, (rl & 0x3f) as usize, l, -1, 0)
                || udprun <= l && self.search1(ud >> 6, (ud & 0x3f) as usize, l, -1, 0)
                || fbprun <= l && self.search1(fb >> 6, (fb & 0x3f) as usize, l, -1, 0)
            {
                break;
            }
            self.length1 += 1;
        }

        let mut p1_sols_arr: Vec<FullCube> = self.p1sols.as_slice().to_vec();
        p1_sols_arr.sort_by_key(|c| c.value);

        let mut max_length2 = 9;
        loop {
            let mut length12 = p1_sols_arr[0].value;
            'out: while length12 < 100 {
                for sol in &p1_sols_arr {
                    if sol.value > length12 {
                        break;
                    }
                    if length12 - sol.length1 > max_length2 {
                        continue;
                    }
                    self.c1.copy_from(sol);
                    let center = *self.c1.center();
                    let parity = self.c1.edge().parity();
                    self.ct2.set(&center, parity);
                    let s2ct = self.ct2.get_ct();
                    let s2rl = self.ct2.get_rl();
                    self.length1 = sol.length1;
                    self.length2 = length12 - sol.length1;

                    if self.search2(s2ct as usize, s2rl as usize, self.length2, 28, 0) {
                        break 'out;
                    }
                }
                length12 += 1;
            }
            max_length2 += 1;
            if length12 != 100 {
                break;
            }
        }

        let arr2idx = self.arr2idx;
        self.arr2[..arr2idx].sort_by_key(|c| c.value);
        let mut index = 0;
        let mut length123;
        let mut max_length3 = 13;
        loop {
            length123 = self.arr2[0].value;
            'out2: while length123 < 100 {
                for i in 0..arr2idx.min(PHASE3_ATTEMPTS) {
                    let cand = &mut self.arr2[i];
                    if cand.value > length123 {
                        break;
                    }
                    let remaining = length123 - cand.length1 - cand.length2;
                    if remaining > max_length3 {
                        continue;
                    }
                    let eparity = self.e12.set_from_cube(cand.edge());
                    let center = *cand.center();
                    let corner_parity = cand.corner().parity();
                    self.ct3.set(&center, eparity ^ corner_parity);
                    let ct = self.ct3.get_ct();
                    let edge = self.e12.get(10);
                    let prun = t.edge3.prun(self.e12.get_sym(&t.edge3) as usize);
                    let lm = 20;

                    if prun <= remaining && self.search3(edge, ct as usize, prun, remaining, lm, 0)
                    {
                        index = i;
                        break 'out2;
                    }
                }
                length123 += 1;
            }
            max_length3 += 1;
            if length123 != 100 {
                break;
            }
        }

        let mut solcube = self.arr2[index].clone();
        self.length1 = solcube.length1;
        self.length2 = solcube.length2;
        let length = length123 - self.length1 - self.length2;

        for &m in &self.move3[..length as usize] {
            solcube.push_move(MOVE3STD[m]);
        }

        let facelet = solcube.reduced_333_facelets();
        let sol = self.search333.solution(&facelet, 21, 1_000_000, 500, 0);
        let len333 = self.search333.length();
        assert!(
            !sol.starts_with("Error"),
            "the reduced 3x3x3 could not be solved ({sol}): {facelet}"
        );
        for m in to_moves(&sol) {
            solcube.push_move(m);
        }

        self.solution = solcube.move_string(t, self.inverse_solution, self.with_rotation);
        self.totlen = self.length1 + self.length2 + length + len333;
    }

    fn search1(&mut self, ct: i32, sym: usize, maxl: i32, lm: i32, depth: usize) -> bool {
        if ct == 0 && maxl < 5 {
            return maxl == 0 && self.init2(sym);
        }
        let c1t = &self.t.center1;
        let mut axis = 0;
        while axis < 27 {
            if axis == lm || axis == lm - 9 || axis == lm - 18 {
                axis += 3;
                continue;
            }
            for power in 0..3 {
                let m = (axis + power) as usize;
                let ctx = c1t.ctsmv[ct as usize][usize::from(c1t.symmove[sym][m])];
                let prun = i32::from(c1t.csprun[(ctx as u32 >> 6) as usize]);
                if prun >= maxl {
                    if prun > maxl {
                        break;
                    }
                    continue;
                }
                let symx = usize::from(c1t.symmult[sym][(ctx & 0x3f) as usize]);
                let ctx = (ctx as u32 >> 6) as i32;
                self.move1[depth] = m;
                if self.search1(ctx, symx, maxl - 1, axis, depth + 1) {
                    return true;
                }
            }
            axis += 3;
        }
        false
    }

    fn init2(&mut self, mut sym: usize) -> bool {
        let t = self.t;
        self.c1.copy_from(&self.c);
        let l1 = self.length1 as usize;
        for &m in &self.move1[..l1] {
            self.c1.push_move(m);
        }

        match t.center1.finish[sym] {
            0 => {
                self.c1.push_move(WF1);
                self.c1.push_move(WB3);
                self.move1[l1] = WF1;
                self.move1[l1 + 1] = WB3;
                self.add1 = true;
                sym = 19;
            }
            12869 => {
                self.c1.push_move(WU1);
                self.c1.push_move(WD3);
                self.move1[l1] = WU1;
                self.move1[l1 + 1] = WD3;
                self.add1 = true;
                sym = 34;
            }
            735_470 => {
                self.add1 = false;
                sym = 0;
            }
            _ => {}
        }
        let center = *self.c1.center();
        let parity = self.c1.edge().parity();
        self.ct2.set(&center, parity);
        let s2ct = self.ct2.get_ct() as usize;
        let s2rl = self.ct2.get_rl() as usize;
        let ctp = i32::from(t.center2.ctprun[s2ct * 70 + s2rl]);

        self.c1.value = ctp + self.length1;
        self.c1.length1 = self.length1;
        self.c1.add1 = self.add1;
        self.c1.sym = sym;
        self.p1_sols_cnt += 1;

        let next = if self.p1sols.len() < PHASE2_ATTEMPTS {
            self.c1.clone()
        } else {
            let mut next = self.p1sols.pop().expect("the queue is full");
            if next.value > self.c1.value {
                next.copy_from(&self.c1);
            }
            next
        };
        self.p1sols.push(next);

        self.p1_sols_cnt == PHASE1_SOLUTIONS
    }

    fn search2(&mut self, ct: usize, rl: usize, maxl: i32, lm: usize, depth: usize) -> bool {
        let t = self.t;
        if ct == 0 && t.center2.ctprun[rl] == 0 && maxl == 0 {
            return self.init3();
        }
        let ckmv2 = &MOVES.ckmv2;
        let skip = &MOVES.skip_axis2;
        let mut m = 0;
        while m < 23 {
            if ckmv2[lm][m] {
                m = skip[m] + 1;
                continue;
            }
            let ctx = usize::from(t.center2.ctmv[ct][m]);
            let rlx = t.center2.rlmv[rl][m] as usize;
            let prun = i32::from(t.center2.ctprun[ctx * 70 + rlx]);
            if prun >= maxl {
                if prun > maxl {
                    m = skip[m];
                }
                m += 1;
                continue;
            }
            self.move2[depth] = MOVE2STD[m];
            if self.search2(ctx, rlx, maxl - 1, m, depth + 1) {
                return true;
            }
            m += 1;
        }
        false
    }

    fn init3(&mut self) -> bool {
        let t = self.t;
        self.c2.copy_from(&self.c1);
        for &m in &self.move2[..self.length2 as usize] {
            self.c2.push_move(m);
        }
        if !self.c2.check_edge() {
            return false;
        }
        let eparity = self.e12.set_from_cube(self.c2.edge());
        let center = *self.c2.center();
        let corner_parity = self.c2.corner().parity();
        self.ct3.set(&center, eparity ^ corner_parity);
        let ct = self.ct3.get_ct();
        // `get(10)` must run before `get_sym`, which rotates the edges.
        let _edge = self.e12.get(10);
        let prun = t.edge3.prun(self.e12.get_sym(&t.edge3) as usize);

        if self.arr2.len() <= self.arr2idx {
            self.arr2.push(self.c2.clone());
        } else {
            self.arr2[self.arr2idx].copy_from(&self.c2);
        }
        let entry = &mut self.arr2[self.arr2idx];
        entry.value =
            self.length1 + self.length2 + prun.max(i32::from(t.center3.prun[ct as usize]));
        entry.length2 = self.length2;
        self.arr2idx += 1;

        self.arr2idx == PHASE2_SOLUTIONS
    }

    fn search3(
        &mut self,
        edge: i32,
        ct: usize,
        prun: i32,
        maxl: i32,
        lm: usize,
        depth: usize,
    ) -> bool {
        if maxl == 0 {
            return edge == 0 && ct == 0;
        }
        let t = self.t;
        let ckmv3 = &MOVES.ckmv3;
        let skip = &MOVES.skip_axis3;
        self.tempe[depth].set_index(edge);
        let mut m = 0;
        while m < 17 {
            if ckmv3[lm][m] {
                m = skip[m] + 1;
                continue;
            }
            let ctx = usize::from(t.center3.ctmove[ct][m]);
            let prun1 = i32::from(t.center3.prun[ctx]);
            if prun1 >= maxl {
                if prun1 > maxl && m < 14 {
                    m = skip[m];
                }
                m += 1;
                continue;
            }
            let ep = self.tempe[depth].edge;
            let edgex = t.edge3.mvrot_index(&ep, m << 3, 10);

            let cord1x = edgex as usize / N_RAW;
            let mut symcord1x = t.edge3.raw2sym[cord1x];
            let symx = (symcord1x & 0x7) as usize;
            symcord1x >>= 3;
            let cord2x = t.edge3.mvrot_index(&ep, m << 3 | symx, 10) % N_RAW as i32;

            let prunx = t
                .edge3
                .prun_relative(symcord1x as usize * N_RAW + cord2x as usize, prun);
            if prunx >= maxl {
                if prunx > maxl && m < 14 {
                    m = skip[m];
                }
                m += 1;
                continue;
            }

            if self.search3(edgex, ctx, prunx, maxl - 1, m, depth + 1) {
                self.move3[depth] = m;
                return true;
            }
            m += 1;
        }
        false
    }
}
