/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.worldcubeassociation.tnoodle.scrambles.Puzzle;
import org.worldcubeassociation.tnoodle.scrambles.PuzzleRegistry;

import java.util.Random;

public class Library {
    static Puzzle getPuzzleFromString(String puzzle) {
        return switch (puzzle) {
            case "222" -> PuzzleRegistry.TWO.getScrambler();
            case "444" -> PuzzleRegistry.FOUR.getScrambler();
            case "555" -> PuzzleRegistry.FIVE.getScrambler();
            case "666" -> PuzzleRegistry.SIX.getScrambler();
            case "777" -> PuzzleRegistry.SEVEN.getScrambler();
            case "minx" -> PuzzleRegistry.MEGA.getScrambler();
            case "pyram" -> PuzzleRegistry.PYRA.getScrambler();
            case "skewb" -> PuzzleRegistry.SKEWB.getScrambler();
            case "sq1" -> PuzzleRegistry.SQ1.getScrambler();
            case "clock" -> PuzzleRegistry.CLOCK.getScrambler();
            default -> PuzzleRegistry.THREE.getScrambler();
        };
    }

    static String generateScramble(String event) {
        Puzzle puzzle = getPuzzleFromString(event);
        return puzzle.generateWcaScramble(new Random());
    }
}
