on:
  pull_request:
  push:
    branches:
      - master
name: CI

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run Clippy
        run: cargo clippy --workspace -- -W clippy::pedantic -W clippy::nursery -D warnings
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Run Tests
        run: cargo test --all
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Check Formatting
        run: cargo fmt --all -- --check